FROM ubuntu:20.04

RUN apt-get -y update
RUN apt-get -y upgrade
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y python3 vim python3-pip git

RUN git clone https://github.com/michahn01/markov_chain_weather_model.git

WORKDIR /markov_chain_weather_model

RUN pip3 install termcolor numpy