FROM centos:8

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install python3 vim python3-pip git

RUN git clone https://github.com/michahn01/markov_chain_weather_model.git

WORKDIR /markov_chain_weather_model

RUN pip3 install termcolor numpy